version: '3.7'
services:

  elasticsearch:
    build: ./elasticsearch
    environment:
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - esdata:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    networks:
    - esnet
    
  kibana:
    build: ./kibana
    links:
    - elasticsearch:elasticsearch
    ports:
    - 5601:5601
    networks:
    - esnet

volumes:
  esdata:
    driver: local
networks:
  esnet: